Repository brave/adblock-rust, pull requests merged in 2025-05, with the labels that each got.

#460 $all
  src/engine.rs
  src/filters/network.rs
Labels: enhancement

#446 Flatbuffers impl
  Cargo.toml
  benches/bench_matching.rs
  benches/bench_serialization.rs
  examples/generate-dat.rs
  js/src/lib.rs
  src/blocker.rs
  src/data_format/mod.rs
  src/data_format/v0.rs
  src/engine.rs
  src/filters/fb_network.rs
  src/filters/mod.rs
  src/filters/network.rs
  src/filters/network_matchers.rs
  src/flatbuffers/fb_network_filter.fbs
  src/flatbuffers/fb_network_filter_generated.rs
  src/lib.rs
  src/network_filter_list.rs
  src/optimizer.rs
  tests/legacy_harness.rs
  tests/live.rs
  tests/ublock-coverage.rs
  tests/unit/blocker.rs
  tests/unit/engine.rs
  tests/unit/filters/network_matchers.rs
Labels: needs-security-review, puLL-Merge

#462 Remove unique_domains_hashes_map from v0 format
  src/data_format/mod.rs
  src/data_format/v0.rs
  tests/unit/data/backwards_compatible_plain.dat
  tests/unit/data/backwards_compatible_tags.dat
  tests/unit/engine.rs
Labels: needs-security-review
